# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{radiant-forum-extension}
  s.version = "0.5.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["spanner"]
  s.date = %q{2010-09-14}
  s.description = %q{Nice clean forums and page comments for inclusion in your radiant site. Derived long ago from beast. Requires the reader extension and share_layouts.}
  s.email = %q{will@spanner.org}
  s.extra_rdoc_files = [
    "README.md"
  ]
  s.files = [
    "README.md",
     "Rakefile",
     "app/controllers/admin/forums_controller.rb",
     "app/controllers/forums_controller.rb",
     "app/controllers/posts_controller.rb",
     "app/controllers/topics_controller.rb",
     "app/models/forum.rb",
     "app/models/moderatorship.rb",
     "app/models/post.rb",
     "app/models/post_attachment.rb",
     "app/models/topic.rb",
     "app/views/admin/forums/_form.html.haml",
     "app/views/admin/forums/edit.html.haml",
     "app/views/admin/forums/index.html.haml",
     "app/views/admin/forums/moderate.html.haml",
     "app/views/admin/forums/new.html.haml",
     "app/views/admin/forums/remove.html.haml",
     "app/views/admin/pages/_edit_commentability.html.haml",
     "app/views/admin/sites/_choose_forum_layout.html.haml",
     "app/views/forums/_forum.html.haml",
     "app/views/forums/index.html.haml",
     "app/views/forums/show.html.haml",
     "app/views/forums/show.rss.builder",
     "app/views/layouts/feed.rss.builder",
     "app/views/monitorships/create.rjs.erb",
     "app/views/monitorships/destroy.rjs.erb",
     "app/views/monitorships/index.html.erb",
     "app/views/pages/_comment.html.haml",
     "app/views/pages/_comments.html.haml",
     "app/views/posts/_attachment.html.haml",
     "app/views/posts/_form.html.haml",
     "app/views/posts/_latest.html.haml",
     "app/views/posts/_post.html.haml",
     "app/views/posts/_post.rss.builder",
     "app/views/posts/_reply.html.haml",
     "app/views/posts/_search.html.haml",
     "app/views/posts/_uploader.html.haml",
     "app/views/posts/edit.html.haml",
     "app/views/posts/index.html.haml",
     "app/views/posts/index.rss.builder",
     "app/views/posts/new.html.haml",
     "app/views/posts/preview.html.haml",
     "app/views/posts/search.html.haml",
     "app/views/posts/search.rss.builder",
     "app/views/posts/show.html.haml",
     "app/views/reader_notifier/post.rhtml",
     "app/views/readers/_extra_controls.html.haml",
     "app/views/readers/show_with_posts.html.haml",
     "app/views/topics/_form.html.haml",
     "app/views/topics/_help.html.haml",
     "app/views/topics/_locked.html.haml",
     "app/views/topics/_topic.html.haml",
     "app/views/topics/_topic.rss.builder",
     "app/views/topics/comments.html.haml",
     "app/views/topics/edit.html.haml",
     "app/views/topics/index.html.haml",
     "app/views/topics/index.rss.builder",
     "app/views/topics/new.html.haml",
     "app/views/topics/show.html.haml",
     "app/views/topics/show.rss.builder",
     "db/migrate/001_create_forum_tables.rb",
     "db/migrate/002_pages_commentable.rb",
     "db/migrate/003_extend_sites.rb",
     "db/migrate/004_sample_layout.rb",
     "db/migrate/005_post_attachments.rb",
     "db/migrate/006_user_relations.rb",
     "db/migrate/007_reader_ownership.rb",
     "db/migrate/008_first_posts.rb",
     "db/migrate/20090824111005_import_helpers.rb",
     "forum_extension.rb",
     "lib/forum_admin_ui.rb",
     "lib/forum_helper.rb",
     "lib/forum_page.rb",
     "lib/forum_reader.rb",
     "lib/forum_reader_notifier.rb",
     "lib/forum_readers_controller.rb",
     "lib/forum_red_cloth3.rb",
     "lib/forum_red_cloth4.rb",
     "lib/forum_site.rb",
     "lib/forum_tags.rb",
     "lib/tasks/radiant_forum_extension_tasks.rake",
     "public/images/admin/forum.png",
     "public/images/admin/new-forum.png",
     "public/images/admin/nominus.png",
     "public/images/admin/noremove.png",
     "public/images/emoticons/angry.gif",
     "public/images/emoticons/bigsmile.gif",
     "public/images/emoticons/confused.gif",
     "public/images/emoticons/cool.gif",
     "public/images/emoticons/cry.gif",
     "public/images/emoticons/devil.gif",
     "public/images/emoticons/neutral.gif",
     "public/images/emoticons/sad.gif",
     "public/images/emoticons/shamed.gif",
     "public/images/emoticons/shocked.gif",
     "public/images/emoticons/smile.gif",
     "public/images/emoticons/surprised.gif",
     "public/images/emoticons/tongue.gif",
     "public/images/emoticons/wink.gif",
     "public/images/forum/attachment.png",
     "public/images/forum/attachment_link.png",
     "public/images/forum/attachment_over.png",
     "public/images/forum/chk_off.png",
     "public/images/forum/chk_on.png",
     "public/images/forum/feed_14.png",
     "public/images/forum/feed_28.png",
     "public/images/forum/post_14.png",
     "public/images/forum/post_14_over.png",
     "public/images/forum/rdo_off.png",
     "public/images/forum/rdo_on.png",
     "public/images/forum/wait_16_grey.gif",
     "public/javascripts/platform/forum.js",
     "public/javascripts/platform/remotecontent.js",
     "public/stylesheets/admin/forum.css",
     "public/stylesheets/platform/forum.css",
     "spec/controllers/admin/forums_controller_spec.rb",
     "spec/controllers/forums_controller_spec.rb",
     "spec/controllers/posts_controller_spec.rb",
     "spec/controllers/topics_controller_spec.rb",
     "spec/datasets/forum_layouts_dataset.rb",
     "spec/datasets/forum_pages_dataset.rb",
     "spec/datasets/forum_readers_dataset.rb",
     "spec/datasets/forum_sites_dataset.rb",
     "spec/datasets/forums_dataset.rb",
     "spec/datasets/posts_dataset.rb",
     "spec/datasets/topics_dataset.rb",
     "spec/lib/forum_admin_ui_spec.rb",
     "spec/lib/forum_page_spec.rb",
     "spec/lib/forum_reader_notification_spec.rb",
     "spec/lib/forum_reader_spec.rb",
     "spec/lib/forum_site_spec.rb",
     "spec/models/forum_spec.rb",
     "spec/models/post_spec.rb",
     "spec/models/topic_spec.rb",
     "spec/spec.opts",
     "spec/spec_helper.rb",
     "vendor/plugins/acts_as_list/README",
     "vendor/plugins/acts_as_list/init.rb",
     "vendor/plugins/acts_as_list/lib/active_record/acts/list.rb",
     "vendor/plugins/acts_as_list/test/list_test.rb"
  ]
  s.homepage = %q{http://github.com/spanner/radiant-forum-extension}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{Forum and Comment Extension for Radiant CMS}
  s.test_files = [
    "spec/controllers/admin/forums_controller_spec.rb",
     "spec/controllers/forums_controller_spec.rb",
     "spec/controllers/posts_controller_spec.rb",
     "spec/controllers/topics_controller_spec.rb",
     "spec/datasets/forum_layouts_dataset.rb",
     "spec/datasets/forum_pages_dataset.rb",
     "spec/datasets/forum_readers_dataset.rb",
     "spec/datasets/forum_sites_dataset.rb",
     "spec/datasets/forums_dataset.rb",
     "spec/datasets/posts_dataset.rb",
     "spec/datasets/topics_dataset.rb",
     "spec/lib/forum_admin_ui_spec.rb",
     "spec/lib/forum_page_spec.rb",
     "spec/lib/forum_reader_notification_spec.rb",
     "spec/lib/forum_reader_spec.rb",
     "spec/lib/forum_site_spec.rb",
     "spec/models/forum_spec.rb",
     "spec/models/post_spec.rb",
     "spec/models/topic_spec.rb",
     "spec/spec_helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<radiant>, [">= 0.9.0"])
      s.add_runtime_dependency(%q<radiant-reader-extension>, [">= 0"])
      s.add_runtime_dependency(%q<paperclip>, [">= 0"])
      s.add_runtime_dependency(%q<will_paginate>, [">= 0"])
    else
      s.add_dependency(%q<radiant>, [">= 0.9.0"])
      s.add_dependency(%q<radiant-reader-extension>, [">= 0"])
      s.add_dependency(%q<paperclip>, [">= 0"])
      s.add_dependency(%q<will_paginate>, [">= 0"])
    end
  else
    s.add_dependency(%q<radiant>, [">= 0.9.0"])
    s.add_dependency(%q<radiant-reader-extension>, [">= 0"])
    s.add_dependency(%q<paperclip>, [">= 0"])
    s.add_dependency(%q<will_paginate>, [">= 0"])
  end
end

